# Generated by Django 5.1.7 on 2025-04-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_members_chatroom_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
