# Generated by Django 5.1.7 on 2025-04-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_encrypted_key_message_iv_message_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='encrypted_key',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='encrypted_session_keys',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
