# Generated by Django 5.1.7 on 2025-05-10 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_suspiciouslinklog_message_is_suspicious_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=36, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('is_malicious', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.DeleteModel(
            name='SuspiciousLinkLog',
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['checked_at'], name='chat_securi_checked_27d388_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['user'], name='chat_securi_user_id_1ba039_idx'),
        ),
    ]
