# Generated by Django 5.1.7 on 2025-05-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_securitylog_delete_suspiciouslinklog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
