# Generated by Django 5.1.7 on 2025-04-26 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 26, 20, 5, 9, 47367, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
