# Generated by Django 5.1.7 on 2025-05-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_key_salt_customuser_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_suspicious_link_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='link_restriction_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspicious_links_count',
            field=models.IntegerField(default=0),
        ),
    ]
