# Generated by Django 5.1.7 on 2025-05-10 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_last_suspicious_link_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blacklist',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
