# Generated by Django 5.1.7 on 2025-05-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hide_last_seen',
            field=models.BooleanField(default=False, verbose_name='Скрывать время последнего входа'),
        ),
    ]
