# Generated by Django 5.1.7 on 2025-05-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_hide_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='restrict_group_invites',
            field=models.BooleanField(default=False, verbose_name='Запретить добавление в групповые чаты'),
        ),
    ]
